 workflows:
  flutter-release:
    name: Flutter Release APK
    environment:
      flutter: stable
    scripts:
      - name: Clean project
        script: |
          flutter clean
          rm -rf android/.gradle
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
